name: Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # We define Postgres here so the backend can run its init checks
      db:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_DB: colorsdb
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Build Docker Images
        run: docker compose build

    
