name: Project CD (Local Deployment)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # CRITICAL: This must match the label you gave your local runner
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Stop and Remove Old Containers
        run: docker compose down || true

      - name: Build and Deploy New Version
        run: docker compose up -d

      - name: Clean Up Unused Images
        run: docker image prune -f
